title: wtfo-jekyll
author: wtfo
email: xhsgg12302@126.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome description for my site , a edition via edit _config.yml
  It will appear in your document head meta (forGoogle search results) 
  and in your feed.xml site description.

# social links
twitter_username: wtfo-twitter
github_username:  wtfo-github

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
